definitions:
  models.Door:
    properties:
      id:
        type: integer
      pathNode:
        $ref: '#/definitions/navigation.PathNode'
        type: object
      section:
        $ref: '#/definitions/models.Section'
        type: object
    type: object
  models.MapItem:
    properties:
      building:
        type: string
      campus:
        type: string
      color:
        type: string
      doors:
        items:
          $ref: '#/definitions/models.Door'
        type: array
      pathNodes:
        items:
          $ref: '#/definitions/navigation.PathNode'
        type: array
      sections:
        items:
          $ref: '#/definitions/models.Section'
        type: array
    type: object
  models.Room:
    properties:
      building:
        type: string
      campus:
        type: string
      color:
        type: string
      description:
        type: string
      doors:
        items:
          $ref: '#/definitions/models.Door'
        type: array
      id:
        type: integer
      name:
        type: string
      pathNode:
        $ref: '#/definitions/navigation.PathNode'
        type: object
      pathNodes:
        items:
          $ref: '#/definitions/navigation.PathNode'
        type: array
      sections:
        items:
          $ref: '#/definitions/models.Section'
        type: array
      tags:
        items:
          type: string
        type: array
    type: object
  models.Section:
    properties:
      end:
        $ref: '#/definitions/navigation.Coordinate'
        type: object
      id:
        type: integer
      start:
        $ref: '#/definitions/navigation.Coordinate'
        type: object
    type: object
  navigation.Coordinate:
    properties:
      x:
        type: integer
      "y":
        type: integer
      z:
        type: integer
    type: object
  navigation.PathNode:
    properties:
      coordinate:
        $ref: '#/definitions/navigation.Coordinate'
        type: object
      group:
        $ref: '#/definitions/navigation.PathNodeGroup'
        type: object
      id:
        type: integer
    type: object
  navigation.PathNodeGroup:
    properties:
      id:
        type: integer
      name:
        type: string
      nodes:
        items:
          $ref: '#/definitions/navigation.PathNode'
        type: array
    type: object
info:
  contact: {}
  license: {}
paths:
  /map:
    get:
      consumes:
      - application/json
      description: Gets map items of available rooms and connector spaces (corridor,
        stairs, etc..) with optional filter parameters
      parameters:
      - description: name of the map items
        in: query
        name: name
        type: string
      - description: floor of the map items
        in: query
        name: floor
        type: integer
      - description: potential alias of the room
        in: query
        name: alias
        type: string
      - description: map item is linked to a certain campus
        in: query
        name: campus
        type: string
      - description: map item is linked to a building
        in: query
        name: building
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.MapItem'
            type: array
      summary: Get All Map Items
      tags:
      - MapController
  /map/floor/{floor}:
    get:
      consumes:
      - application/json
      description: Gets all map items of available rooms and connector spaces (corridor,
        stairs, etc..) of a certain floor
      operationId: get-room-list-floor
      parameters:
      - description: filter map items by floor
        in: path
        name: floor
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.MapItem'
            type: array
      summary: Get All Map Items from a certain floor
      tags:
      - MapController
  /navigation/dir:
    get:
      consumes:
      - application/json
      description: Gets the navigation route for a start and end room
      parameters:
      - description: the start room name
        in: query
        name: startroom
        type: string
      - description: the end room name
        in: query
        name: endroom
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/navigation.Coordinate'
            type: array
      summary: Get Navigation Route
      tags:
      - NavigationController
  /roomlist/:
    get:
      consumes:
      - application/json
      description: Gets all available rooms
      operationId: get-room-list
      parameters:
      - description: room name
        in: query
        name: name
        type: string
      - description: floor of the room
        in: query
        name: floor
        type: integer
      - description: potential alias of the room
        in: query
        name: alias
        type: string
      - description: rooms that contain the query string in name, alias or description
        in: query
        name: room
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Room'
            type: array
      summary: Get Room List
      tags:
      - RoomController
  /roomlist/floor/{floor}:
    get:
      consumes:
      - application/json
      description: Gets all available rooms for a certain floor
      operationId: get-room-list-floor
      parameters:
      - description: filter rooms by floor
        in: path
        name: floor
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Room'
            type: array
      summary: Get Room List From Floor
      tags:
      - RoomController
  /roomlist/room/{name}:
    get:
      consumes:
      - application/json
      description: Gets a specify room by its unique name
      operationId: get-room
      parameters:
      - description: get room by name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Room'
      summary: Get Room by Name
      tags:
      - RoomController
swagger: "2.0"
