definitions:
  models.Door:
    properties:
      id:
        type: integer
      pathNode:
        $ref: '#/definitions/navigation.PathNode'
        type: object
      sequence:
        $ref: '#/definitions/models.Sequence'
        type: object
    type: object
  models.Room:
    properties:
      alias:
        items:
          type: string
        type: array
      color:
        type: string
      description:
        type: string
      doors:
        items:
          $ref: '#/definitions/models.Door'
        type: array
      floor:
        type: integer
      id:
        type: integer
      name:
        type: string
      sections:
        items:
          $ref: '#/definitions/models.Sequence'
        type: array
    type: object
  models.Sequence:
    properties:
      end:
        $ref: '#/definitions/navigation.Coordinate'
        type: object
      id:
        type: integer
      start:
        $ref: '#/definitions/navigation.Coordinate'
        type: object
    type: object
  models.ShoppingItem:
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  navigation.Coordinate:
    properties:
      x:
        type: integer
      "y":
        type: integer
      z:
        type: integer
    type: object
  navigation.PathNode:
    properties:
      connectedNodes:
        items:
          $ref: '#/definitions/navigation.PathNode'
        type: array
      coordinate:
        $ref: '#/definitions/navigation.Coordinate'
        type: object
      group:
        $ref: '#/definitions/navigation.PathNodeGroup'
        type: object
      id:
        type: integer
    type: object
  navigation.PathNodeGroup:
    properties:
      id:
        type: integer
      name:
        type: string
      nodes:
        items:
          $ref: '#/definitions/navigation.PathNode'
        type: array
    type: object
info:
  contact: {}
  license: {}
paths:
  /roomlist/:
    get:
      consumes:
      - application/json
      description: Gets all available rooms
      operationId: get-room-list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Room'
            type: array
      summary: Get Room List
      tags:
      - RoomController
  /shoppinglist/list/:
    get:
      consumes:
      - application/json
      description: Gets all shopping items
      operationId: get-shopping-list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ShoppingItem'
            type: array
      summary: Get Shopping List
      tags:
      - ShoopingListController
swagger: "2.0"
